version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    ignore:
      # ignore all patch updates 
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
