name: Deploy to Heroku
concurrency: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # threatdragon is the working area on docker hub so use this area
  # owasp/threat-dragon is the final release area so DO NOT use that
  IMAGE_NAME: threatdragon/owasp-threat-dragon
  HEROKU_APP: threatdragon-v2

# for security reasons the github actions are pinned to specific release versions
jobs:
  latest_docker:
    name: Latest docker
    runs-on: ubuntu-22.04
    if: github.repository == 'OWASP/threat-dragon'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.9.0
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3.3.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        # using an image name without a :tag gives 'latest' image
        id: docker_build
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  ${{ env.IMAGE_NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy:
    name: Upload to Heroku
    runs-on: ubuntu-22.04
    needs: [latest_docker]
    # There is an action to build and deploy a heroku app
    # We already built the container though, so why not just re-tag and push
    steps:
      - name: Pull docker image
        run: docker pull ${{ env.IMAGE_NAME }}

      - name: Login to Heroku Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Tag Heroku image
        run: docker tag ${{ env.IMAGE_NAME }} registry.heroku.com/${{ env.HEROKU_APP }}/web

      - name: Push to Heroku
        run: docker push registry.heroku.com/${{ env.HEROKU_APP }}/web

      - name: Deploy to Heroku
        run: heroku container:release web --app ${{ env.HEROKU_APP }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  smoke_tests:
    name: Smoke tests
    runs-on: ubuntu-22.04
    needs: [deploy]
    defaults:
      run:
        working-directory: td.vue
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '18'

      - name: Cache NPM dir
        uses: actions/cache@v3.3.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install packages
        run: npm clean-install

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@v1.0.1
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Run cross-browser smoke tests
        run: npm run test:e2e-smokes

  rollback:
    name: Rollback on fail
    runs-on: ubuntu-22.04
    needs: [smoke_tests]
    if: ${{ failure() }}
    steps:
      - name: Rollback
        run: heroku rollback --app ${{ env.HEROKU_APP }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
