name: Run e2e test
on:
  push:
jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get latest Firefox
        uses: browser-actions/setup-firefox@latest

      - name: Get latest Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Install NPM Dependencies
        run: cd td.vue && npm ci

      - name: Run e2e tests
        run: cd td.vue && npm run test:e2e-ci
