name: Housekeeping
on:
  # Run daily at 7:00
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    steps:
      - name: Delete stale workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 182
          keep_minimum_runs: 3
