name: Push stable tag (temporary, single-use)
on:
  push:
    branches: [ feature/313-clarify-docker-usage ]
env:
  image_name: "threatdragon/owasp-threat-dragon"
jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Setup dockerx cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Pull last release version
        run: docker pull threatdragon/owasp-threat-dragon:v1.5.8

      - name: Tag stable
        run: docker tag threatdragon/owasp-threat-dragon:v1.5.8 threatdragon/owasp-threat-dragon:stable

      - name: Push stable
        run: docker push threatdragon/owasp-threat-dragon:stable
