name: Build/Release Desktop

on:
  push:
    # only for version 2.x.x releases and release candidates
    tags:
      - v2.?.?*

env:
  image_name: "threatdragon/owasp-threat-dragon"

jobs:
  server_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: td.server
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM dir
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: lint
        run: npm run lint

      - name: Unit test
        run: npm run test:unit

  site_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: td.vue
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM dir
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: lint
        run: npm run lint

      - name: Unit test
        run: npm run test:unit

  desktop_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: td.vue
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM dir
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: lint
        run: npm run lint
  
      - name: Unit test
        run: npm run test:desktop

  release_desktop:
    runs-on: ${{ matrix.config.os }}
    needs: [desktop_unit_tests, site_unit_tests]
    strategy:
      matrix:
        config:
          - { os: macos-latest, os_short: osx }
          - { os: ubuntu-latest, os_short: lin }
          - { os: windows-latest, os_short: win }
    defaults:
      run:
        working-directory: td.vue
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM dir
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build installer
      - run: npm run build:desktop

      - name: Prepare for app notarization
        if: startsWith(matrix.config.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8

      # Win and OSX will just publish to the GH Release Draft
      # (and create it if needed based on version)
      # Snap publishing fails using this plugin,
      # so special care is needed for linux
      - name: Build/release Electron app
        if: ${{ !startsWith(matrix.config.os, 'ubuntu') }}
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          # follow Comodo signing instructions
          # comodosslstore.com/resources/comodo-code-signing-certificate-instructions
          windows_certs: ${{ secrets.windows_certs }}
          windows_certs_password: ${{ secrets.windows_certs_password }}

          package_root: td.vue
        env:
          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}

      # Build all linux images EXCEPT for the snap, with publish always
      # Snaps will not publish, even with snapcraft installed
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm run electron-builder -- --linux AppImage deb rpm --publish always
        if: startsWith(matrix.config.os, 'ubuntu')

      # Build the snap, but do not publish
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm run electron-builder -- --linux snap
        if: startsWith(matrix.config.os, 'ubuntu')

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        with:
          # Log in to Snap Store
          snapcraft_token: ${{ secrets.snapcraft_token }}
        if: startsWith(matrix.config.os, 'ubuntu')

      - shell: bash
        run: snapcraft upload --release=stable installers/threat-dragon-desktop*.snap
        if: startsWith(matrix.config.os, 'ubuntu')

  release-docker:
    runs-on: ubuntu-latest
    needs: [server_unit_tests, site_unit_tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Setup dockerx cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ env.image_name }}:${{ env.RELEASE_VERSION }},stable
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
