name: Build/Release Desktop

on:
  push:
    # TODO: comment this out, only used for development
    branches: [ sign-images ]
    # only for version 2.x.x releases and release candidates
    tags:
      - v2.?.?*

env:
  image_name: "threatdragon/owasp-threat-dragon"

jobs:
  site_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: td.vue
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache NPM dir
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: lint
        run: npm run lint

      - name: Unit test
        run: npm run test:unit

  server_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: td.server
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache NPM dir
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: lint
        run: npm run lint

      - name: Unit test
        run: npm run test:unit

  desktop_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: td.vue
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache NPM dir
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: lint
        run: npm run lint
  
      - name: Unit test
        run: npm run test:desktop

  desktop_e2e_tests:
    runs-on: windows-latest
    needs: [desktop_unit_tests, site_unit_tests]
    defaults:
      run:
        working-directory: td.vue
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ubuntu-latest does not find this chrome driver
      # so until this is fixed, use only windows-latest
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.0.1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache NPM dir
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build application
        # test only so do not publish
        run: npm run build:desktop -- --publish=never

      # works for macos-latest running locally but pipeline times out 
      # so until this is fixed, use only windows-latest
      - name: End to end tests
        run: npm run test:e2e:desktop

  desktop_installers:
    runs-on: ${{ matrix.config.os }}
    needs: [desktop_unit_tests, site_unit_tests, desktop_e2e_tests]
    strategy:
      matrix:
        config:
          - { os: macos-latest, os_short: osx }
          - { os: ubuntu-latest, os_short: lin }
          - { os: windows-latest, os_short: win }
    defaults:
      run:
        working-directory: td.vue
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.0.1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache NPM dir
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build installer
        env:
          # github token is automatically provided to the action
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:desktop

      - name: Prepare for app notarization
        # Import Apple API key for app notarization on macOS
        # see github.com/samuelmeuli/action-electron-builder#notarization
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.API_KEY_ID }}.p8
        if: startsWith(matrix.config.os, 'macos')

      # Publish MacOS to GH Release Draft based on version (and create if needed)
      # - name: Release for MacOS
      #   env:
          # macOS notarization API IDs
          # see github.com/samuelmeuli/action-electron-builder#notarization
      #     API_KEY_ID: ${{ secrets.API_KEY_ID }}
      #     API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
          # macOS signing certificate and password
          # see github.com/samuelmeuli/action-electron-builder#code-signing
      #     CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
      #     CSC_LINK:  ${{ secrets.MAC_CERTS }}
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npm run build:desktop -- --mac --publish always 
      #   if: startsWith(matrix.config.os, 'macos')

      # Win and OSX will just publish to the GH Release Draft
      # (and create it if needed based on version)
      # Snap publishing fails using this plugin,
      # so special care is needed for linux
      # - name: Release for Windows and MacOS
      #   uses: samuelmeuli/action-electron-builder@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
      #     release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # see github.com/samuelmeuli/action-electron-builder#code-signing
      #     mac_certs: ${{ secrets.MAC_CERTS }}
      #     mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}

          # follow Comodo signing instructions
          # comodosslstore.com/resources/comodo-code-signing-certificate-instructions
      #     windows_certs: ${{ secrets.WINDOWS_CERTS }}
      #     windows_certs_password: ${{ secrets.WINDOWS_CERTS_PASSWORD }}

      #     package_root: td.vue
      #   env:
          # macOS notarization API key and ID
      #     API_KEY_ID: ${{ secrets.API_KEY_ID }}
      #     API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
      #   if: ${{ !startsWith(matrix.config.os, 'ubuntu') }}

      # Build all linux images EXCEPT for the snap, with publish always
      # Snaps will not publish, even with snapcraft installed
      - name: Release for Linux
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:desktop -- --linux AppImage deb rpm --publish always
        if: startsWith(matrix.config.os, 'ubuntu')

      # Build the snap, but do not publish
      - name: Build snap installer
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron-builder -- --linux snap
        if: startsWith(matrix.config.os, 'ubuntu')

      - name: Login to Snap Store
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        with:
          # Log in to Snap Store
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
        if: startsWith(matrix.config.os, 'ubuntu')

      # TODO: Uncomment when ready to start deploying again
      # - name: Upload snap
      #   shell: bash
      #   run: snapcraft upload --release=stable installers/threat-dragon-desktop*.snap
      #   if: startsWith(matrix.config.os, 'ubuntu')

  dockerhub_release:
    runs-on: ubuntu-latest
    needs: [server_unit_tests, site_unit_tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Setup dockerx cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # TODO: Uncomment when ready to start deploying again
      # - name: Build and push to Docker Hub
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: ${{ startsWith(github.ref, 'refs/tags/v') }}
      #     tags: ${{ env.image_name }}:${{ env.RELEASE_VERSION }},stable
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache

# TODO: Can we add a table with shasums to the release description?
# Is it worth automating that portion?
