name: Trivy Scan
on:
  # Run daily at 7:00
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

# for security reasons the github actions are pinned to specific release versions
jobs:
  housekeeping:
    name: Scan with Trivy
    runs-on: ubuntu-22.04

    steps:
      - name: Delete stale workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 91
          keep_minimum_runs: 3

